### ISSUE TITLE
modporter install instructions - httpd.conf on mac osX

### ISSUE THREAD

**Issue by pjammer** [actionrails/modporter#3]
in order for this to work, i needed to add the following to my httpd.conf file:

```
LoadModule apreq_module libexec/apache2/mod_apreq2.so
LoadModule porter_module libexec/apache2/mod_porter.so
```

on modporter.com/install you mention the following, but this config wouldn't load when i tried to restart apache ( httpd -k restart )

```
LoadModule apreq_module modules/mod_apreq2.so
LoadModule porter_module modules/mod_porter.so
```

thanks.

**Comment by NZKoz** [comment]
Thanks, I've fixed this and pushed the change
