### ISSUE TITLE
mod_porter -> rails attachment_fu fails to validate when nested upload is empty

### ISSUE THREAD

**Issue by jonn** [actionrails/modporter#5]
Not confident that this is a bug in ModPorter as opposed to the modporter-plugin for rails or something on the rails/attachment_fu side of things, but it seems this should be addressed in the modified request parameters passed up from mod_porter.

Rails resources can be nested in forms allowing a parent and child resource to be created with one form POST.  In the case where the parent and child are both uploads and the child can be nil, attachment validation succeeds without mod_porter, but fails with mod_porter.

I have a case where a "song" and a corresponding but optional "picture" can be uploaded together.

Picture-less non-mod_porter request parameters (works on rails sans mod_porter):

<pre>
Parameters: {"commit"=>"Upload", "authenticity_token"=>"shtjxeSF2BUZS4efZitRgnrmdZYJE0eFKoY3iprVZWU=", "X-Progress-ID"=>"5325793944", "band_id"=>"OTM4", "song"=>{"uploaded_data"=>#&lt;File:/tmp/RackMultipart7306-3&gt;}}
</pre>

When mod_porter is added, rails reports the request parameters like this (fails because "default_picture_attributes", which can be null/nil, is an empty string):

<pre>
Parameters: {"commit"=>"Upload", "authenticity_token"=>"shtjxeSF2BUZS4efZitRgnrmdZYJE0eFKoY3iprVZWU=", "X-Progress-ID"=>"5359685724", "band_id"=>"OTM4", "song"=>{"uploaded_data"=>{"content_type"=>"application/x-download", "signature"=>"giUmiQS+ppAkY1W0MKjXY4AQzmk=", "filename"=>"Velvet Sunshine.mp3", "path"=>"/tmp/apreq4Kqefr"}, "default_picture_attributes"=>{"uploaded_data"=>""}}}
</pre>

When the "picture" is included in the POST ("default_picture_attributes" is an image file) the uploads validate correctly and all goes well with and without mod_porter.

As a quick fix to my problem, I added the following inside the <code>porter_params.each do</code> loop of the <code>normalize_mod_porters</code> method of the ModPorter Filter provided by the modporter-plugin for Rails:

<pre>
reqParam = request.parameters[file_param[0,file_param.index('[')]]
reqParam.each do |part|
  if !part[1].is_a?(UploadedFile) && part[1]["uploaded_data"] && part[1]["uploaded_data"].blank?
    reqParam.delete(part[0])
  end
end
</pre>

While this makes uploads pass attachment validation regardless of the presence of the optional nested upload, it seems like this isn't really <i>the answer</i> and mod_porter should probably just not include any request parameter info for absent uploads so the altered request parameters correspond more closely to what is seen without mod_porter.  But I may be off as I'm sure there are many factors to consider outside of my use case.

Thanks for the great module!
- Jonn

**Comment by NZKoz** [comment]
yeah, the current behaviour of blindly including an empty string for the upload contents is kinda nasty.  However it was consistent with what safari sent when I was tinkering.  You could change:

http://github.com/actionrails/modporter/blob/3a77a621bf32db8c8e4f6cff86bf61ec1e7bafe6/mod_porter.c#L293-299

to just return APR_SUCCESS and see what happens?

**Comment by jonn** [comment]
Yes, indeed.  Changed this per your instructions and removed my modporter-plugin hack and uploads validate correctly with and without the presence of the optional picture file.

Thank you very much!

I have tested with Firefox 3.5.1, Safari 4.0.2, and Camino 2.0b3 and all behave nicely and consistently for me.

Thanks again,
- Jonn

**Comment by NZKoz** [comment]
OK, give me a few days to think of a way this thing could break.  Then I'll make those changes.

**Comment by NZKoz** [comment]
I've pushed this change now in b5c949503ef20d29fc14412c93cb8e4ed6e1e993
